import type { Preset } from './types';

export const TERRAIN_PRESETS: Record<string, Preset> = {
  ocean: {
    name: 'Ocean',
    prompt: 'seamless tileable top-down 2D strategy game terrain texture, deep ocean water, rich cobalt blue with subtle whitecap ripple patterns, hand-painted illustration style like Battle for Wesnoth, viewed perfectly from above, no perspective, uniform tile pattern, natural organic water texture variation, ancient strategy game art, warm color grading',
    color: '#4169E1',
    file: 'terrain_ocean',
    w: 256, h: 256,
  },
  plains: {
    name: 'Plains',
    prompt: 'seamless tileable top-down 2D strategy game terrain texture, flat grassy plains, light yellowish-green grass with subtle variation, scattered wildflowers and pebbles, hand-painted illustration style like Battle for Wesnoth, viewed perfectly from above, no perspective, warm sun-lit color palette, soft green tones',
    color: '#90EE90',
    file: 'terrain_plains',
    w: 256, h: 256,
  },
  grassland: {
    name: 'Grassland',
    prompt: 'seamless tileable top-down 2D strategy game terrain texture, natural grassy meadow, soft muted sage-green short grass with gentle tonal variation, earthy yellow-olive undertones, subdued low-contrast palette, NOT saturated, NOT neon green, calm even lighting, faint tiny clover and dry herb details, classic Civilization 2 style, no trees no rocks, perfectly flat top-down view, painterly illustration',
    color: '#32CD32',
    file: 'terrain_grassland',
    w: 256, h: 256,
  },
  forest: {
    name: 'Forest',
    prompt: 'seamless tileable top-down 2D strategy game terrain texture, deciduous forest canopy viewed from directly above, dark green round tree crowns with dappled sunlight gaps between them, hand-painted illustration style like Battle for Wesnoth, rich greens and deep shadows between trees, organic natural pattern, warm forest light',
    color: '#228B22',
    file: 'terrain_forest',
    w: 256, h: 256,
  },
  jungle: {
    name: 'Jungle',
    prompt: 'seamless tileable top-down 2D strategy game terrain texture, dense tropical jungle canopy from directly above, very dark deep green with large overlapping broad leaves, exotic tropical feel, hand-painted illustration style like Battle for Wesnoth, deep shadow contrasts, dense thick foliage, humid tropical atmosphere',
    color: '#1B7A3D',
    file: 'terrain_jungle',
    w: 256, h: 256,
  },
  hills: {
    name: 'Hills',
    prompt: 'seamless tileable top-down 2D strategy game terrain texture, rolling hills terrain viewed from above, earthy yellowish-brown and green tones with subtle elevation shading, sparse dry grass and dirt patches, hand-painted illustration style like Battle for Wesnoth, warm earthy Mediterranean hills',
    color: '#8FBC8F',
    file: 'terrain_hills',
    w: 256, h: 256,
  },
  mountains: {
    name: 'Mountains',
    prompt: 'seamless tileable top-down 2D strategy game terrain texture, rocky mountain terrain viewed directly from above, gray stone with white snow at peaks, bare rock faces with crevices, hand-painted illustration style like Battle for Wesnoth, cool gray and white palette with dramatic rock shadows, high altitude alpine feel',
    color: '#696969',
    file: 'terrain_mountains',
    w: 256, h: 256,
  },
  desert: {
    name: 'Desert',
    prompt: 'seamless tileable top-down 2D strategy game terrain texture, arid sandy desert viewed from directly above, warm golden-orange sand with subtle dune ripple patterns and occasional pebbles, hand-painted illustration style like Battle for Wesnoth, hot dry atmosphere, rich sandy ochre and sienna tones',
    color: '#F4A460',
    file: 'terrain_desert',
    w: 256, h: 256,
  },
  swamp: {
    name: 'Swamp',
    prompt: 'seamless tileable top-down 2D strategy game terrain texture, murky swamp wetland viewed from above, dark brown-green muddy water with clumps of dead grass and moss, murky bubbles, hand-painted illustration style like Battle for Wesnoth, gloomy dark atmosphere, sickly olive and brown tones',
    color: '#5B3A1E',
    file: 'terrain_swamp',
    w: 256, h: 256,
  },
  tundra: {
    name: 'Tundra',
    prompt: 'seamless tileable top-down 2D strategy game terrain texture, frozen tundra viewed from directly above, cold pale gray-blue ground with sparse dead brown grass and frost patterns, icy patches, hand-painted illustration style like Battle for Wesnoth, cold bleak winter atmosphere, desaturated blue-gray palette',
    color: '#B0C4DE',
    file: 'terrain_tundra',
    w: 256, h: 256,
  },
  arctic: {
    name: 'Arctic',
    prompt: 'seamless tileable top-down 2D strategy game terrain texture, arctic snow and ice field viewed from directly above, pure white snow with subtle blue shadow patterns in snow drifts, cracked ice surface, hand-painted illustration style like Battle for Wesnoth, clean crisp cold atmosphere, white and pale blue palette',
    color: '#F0F8FF',
    file: 'terrain_arctic',
    w: 256, h: 256,
  },
  river: {
    name: 'River',
    prompt: 'seamless tileable top-down 2D strategy game terrain texture, flowing river water viewed from directly above, clear blue-green water with subtle current ripples and small rocks, shallow riverbed visible, hand-painted illustration style like Battle for Wesnoth, fresh clean water feel, bright azure and teal tones',
    color: '#3b82f6',
    file: 'terrain_river',
    w: 256, h: 256,
  },
};

export const FEATURE_PRESETS: Record<string, Preset> = {
  forest: {
    name: 'Forest',
    prompt: 'isolated terrain feature sprite for 2D strategy game tile, a dense thick forest grove with many overlapping rounded deciduous tree canopies packed tightly together viewed from directly above (90-degree bird\'s-eye top-down view), the entire lower 90 percent of the image filled with interlocking circular leafy canopy tops that continue all the way down to the bottom edge, the feature fills a square tile footprint (flat square view, not a diamond or isometric shape), no gaps showing the ground or trunks, rich deep green hand-painted canopies with varied leaf clusters and soft warm highlights, classic Civilization 2 or Wesnoth strategy game art style, clean solid pale neutral background for easy background removal, portrait 256x384, no side view, no ground, no trunks, no drop shadows',
    color: '#228B22',
    file: 'terrain_forest_feature',
    w: 256, h: 384,
  },
  jungle: {
    name: 'Jungle',
    prompt: 'isolated terrain feature sprite for 2D strategy game tile, dense tropical jungle canopy viewed from directly above (90-degree bird\'s-eye top-down view), large overlapping dark green palm fronds and broad tropical leaves seen flat from above, circular canopy shapes fill the lower 90 percent of the image and continue all the way down to the bottom edge, the feature fills a square tile footprint (flat square view, not a diamond or isometric shape), very lush and dense, trunk and ground hidden, classic Civilization 2 or Wesnoth strategy game art style, hand-painted, clean solid pale neutral background for easy background removal, portrait 256x384, no side view, no ground',
    color: '#1B7A3D',
    file: 'terrain_jungle_feature',
    w: 256, h: 384,
  },
  hills: {
    name: 'Hills',
    prompt: 'isolated terrain feature sprite for 2D strategy game tile, a single large rounded grassy hill seen from directly above (90-degree top-down view), gently rounded smooth grassy crown with muted earthy olive-green grass, soft lighter yellow-green highlight on the top of the mound and soft darker green shading around the outer rim and in the shallow dips, subtle short grass tuft texture scattered across the surface, the hill fills the entire lower 90 percent of the image edge to edge and is cut off by the bottom edge so it touches the bottom border with no gap below it, the feature fills a square tile footprint (flat square view, not a diamond or isometric shape), no trees no rocks no paths, classic Civilization 2 or Wesnoth strategy game art style, hand-painted, clean solid pale neutral background for easy background removal, portrait 256x384',
    color: '#8FBC8F',
    file: 'terrain_hills_feature',
    w: 256, h: 384,
  },
  mountains: {
    name: 'Mountains',
    prompt: 'isolated terrain feature sprite for 2D strategy game tile, a compact mountain range that fills the lower 90 percent of the image, several craggy grey rocky peaks forming one continuous tall mountain mass, the mass spans the full width touching both the left and right edges of the image, the rocky base is cut off by the bottom edge so the mountains touch the bottom border with no gap below, the peaks rise tall filling the vertical space so only the top 10 percent of the image is empty background, no separate flat base plate, no empty background gap or border around the mountains, flat 90-degree bird\'s-eye top-down view (not diamond, not isometric), grey craggy stone with white snow on the high points, classic Civilization 2 or Wesnoth strategy game art style, hand-painted, clean solid pale neutral background for easy background removal, portrait 256x384',
    color: '#696969',
    file: 'terrain_mountains_feature',
    w: 256, h: 384,
  },
  swamp: {
    name: 'Swamp',
    prompt: 'isolated terrain feature sprite for 2D strategy game tile, a gnarled dead tree viewed from a steep top-down angle, twisted bare dark branches radiating outward seen from above, mossy bark, dark murky swamp water visible at the base, the tree rests on the bottom edge and fills the lower 90 percent of the image, the feature fills a square tile footprint (flat square view, not a diamond or isometric shape), classic Civilization 2 or Wesnoth strategy game art style, hand-painted, clean solid pale neutral background for easy background removal, portrait 256x384, no side view',
    color: '#5B3A1E',
    file: 'terrain_swamp_feature',
    w: 256, h: 384,
  },
};
